/**
 * Browser year stub — 1995
 * GENERATED by scripts/gen_year_shims.py — do not hand-fork.
 */
(function () {
  "use strict";
  if (window.ITT && ITT.bootBrowserYear) {
    ITT.bootBrowserYear("1995");
    return;
  }
  if (!window.ITT || !ITT.Browser || !ITT.configs || !ITT.configs["1995"]) {
    console.error("ITT 1995 bootstrap: missing util/core/config scripts");
    return;
  }
  ITT.Browser.create(ITT.configs["1995"]);
})();
