/**
 * Browser year stub — 2018
 * GENERATED by scripts/gen_year_shims.py — do not hand-fork.
 */
(function () {
  "use strict";
  if (window.ITT && ITT.bootBrowserYear) {
    ITT.bootBrowserYear("2018");
    return;
  }
  if (!window.ITT || !ITT.Browser || !ITT.configs || !ITT.configs["2018"]) {
    console.error("ITT 2018 bootstrap: missing util/core/config scripts");
    return;
  }
  ITT.Browser.create(ITT.configs["2018"]);
})();
