/**
 * Browser year stub — 2007
 * GENERATED by scripts/gen_year_shims.py — do not hand-fork.
 */
(function () {
  "use strict";
  if (window.ITT && ITT.bootBrowserYear) {
    ITT.bootBrowserYear("2007");
    return;
  }
  if (!window.ITT || !ITT.Browser || !ITT.configs || !ITT.configs["2007"]) {
    console.error("ITT 2007 bootstrap: missing util/core/config scripts");
    return;
  }
  ITT.Browser.create(ITT.configs["2007"]);
})();
