/**
 * Immersion year stub — 2002
 * GENERATED by scripts/gen_year_shims.py — do not hand-fork.
 */
(function () {
  "use strict";
  var ITT = window.ITT || (window.ITT = {});
  ITT._immersionYear = "2002";
  var scripts = document.getElementsByTagName("script");
  var me = document.currentScript || scripts[scripts.length - 1];
  var base = (me && me.src) ? me.src.replace(/\/[^/]*$/, "/") : "/js/";
  var el = document.createElement("script");
  el.src = base + "immersion/boot.js?v=20260926cavern";
  el.async = true;
  (document.head || document.documentElement).appendChild(el);
})();
