/**
 * Immersion feature registry — single source of truth per year.
 * SRP: which modules load for which year (data only) + register helpers.
 * Add a year here; do NOT copy FEATURES maps into immersion-199x.js.
 */
(function (global) {
  "use strict";
  var ITT = global.ITT || (global.ITT = {});

  /** Feature list for Immersion.create orchestrator */
  var features = ITT.ImmersionFeatures || (ITT.ImmersionFeatures = []);

  /**
   * Push a feature spec { id, needs?, init }.
   * Prefer this over bare ImmersionFeatures.push in new modules.
   */
  features.register = function (spec) {
    features.push(spec);
    return spec;
  };

  /**
   * Register a page-local boot feature (digg/reddit/maps style).
   * Single IIFE responsibility: define boot + register + once-guard.
   *
   * @param {object} opts
   * @param {string} opts.id feature id
   * @param {function} opts.boot function(doc)
   * @param {string} [opts.ns] expose as ITT[ns] (default: id)
   * @param {string} [opts.featureKey] cfg.features key (default: id)
   * @param {boolean} [opts.autoBoot=true] DOM-ready boot for standalone pages
   */
  features.registerLocal = function (opts) {
    if (!opts || !opts.id || typeof opts.boot !== "function") {
      throw new Error("ImmersionFeatures.registerLocal requires id + boot");
    }
    var id = opts.id;
    var ns = opts.ns || id;
    var featureKey = opts.featureKey || id;
    var boot = opts.boot;
    var autoBoot = opts.autoBoot !== false;
    var attr = "data-itt-feat-" + id;

    function bootOnce(doc) {
      doc = doc || document;
      try {
        if (doc.documentElement && doc.documentElement.getAttribute(attr) === "1") return;
        if (doc.documentElement) doc.documentElement.setAttribute(attr, "1");
      } catch (e) { /* */ }
      boot(doc);
    }

    ITT[ns] = { boot: bootOnce };
    features.push({
      id: id,
      needs: function (cfg) {
        return !cfg.features || cfg.features[featureKey] !== false;
      },
      init: function () {
        bootOnce(document);
      }
    });

    if (autoBoot) {
      if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", function () {
          bootOnce(document);
        });
      } else {
        bootOnce(document);
      }
    }
    return bootOnce;
  };

  /** @type {Object.<string, string[]>} paths relative to js/ */
  ITT.IMMERSION_FEATURES_BY_YEAR = {
    "1994": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/geocities.js",
      "immersion/media-1994.js",
      "immersion/one-thing-machines.js",
      "immersion/source-flows.js"
    ],
    "1995": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/one-thing-machines.js"
    ],
    "1996": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/hotmail.js",
      "immersion/geocities.js",
      "immersion/plugin.js",
      "immersion/yahoo.js",
      "immersion/excite.js",
      "immersion/one-thing-machines.js"
    ],
    "1997": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/hotmail.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/yahoo.js",
      "immersion/icq.js",
      "immersion/one-thing-machines.js"
    ],
    "1998": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/hotmail.js",
      "immersion/plugin.js",
      "immersion/source-flows.js"
    ],
    "1999": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/aim.js",
      "immersion/sourceforge.js"
    ],
    "2000": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/mapquest.js"
    ],
    "2005": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/technorati.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/friendster.js",
      "immersion/kazaa.js",
      "immersion/myspace.js",
      "immersion/itunes.js",
      "immersion/wordpress.js",
      "immersion/linkedin.js",
      "immersion/adsense.js",
      "immersion/bloglines.js",
      "immersion/gmail.js",
      "immersion/facebook.js",
      "immersion/flickr.js",
      "immersion/youtube.js",
      "immersion/maps.js",
      "immersion/reddit.js",
      "immersion/digg.js",
      "immersion/podcasts.js",
      "immersion/delicious.js",
      "immersion/housingmaps.js",
      "immersion/feedburner.js",
      "immersion/netflix.js",
      "immersion/pandora.js",
      "immersion/source-flows.js"
    ],
    "2006": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/technorati.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/friendster.js",
      "immersion/kazaa.js",
      "immersion/myspace.js",
      "immersion/itunes.js",
      "immersion/wordpress.js",
      "immersion/linkedin.js",
      "immersion/adsense.js",
      "immersion/bloglines.js",
      "immersion/gmail.js",
      "immersion/facebook.js",
      "immersion/flickr.js",
      "immersion/youtube.js",
      "immersion/maps.js",
      "immersion/reddit.js",
      "immersion/digg.js",
      "immersion/podcasts.js",
      "immersion/delicious.js",
      "immersion/housingmaps.js",
      "immersion/feedburner.js",
      "immersion/twitter.js",
      "immersion/docs.js",
      "immersion/aws.js",
      "immersion/reader.js",
      "immersion/netflix.js",
      "immersion/one-thing-machines.js"
    ],
    "2007": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/technorati.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/friendster.js",
      "immersion/kazaa.js",
      "immersion/myspace.js",
      "immersion/itunes.js",
      "immersion/wordpress.js",
      "immersion/linkedin.js",
      "immersion/adsense.js",
      "immersion/bloglines.js",
      "immersion/gmail.js",
      "immersion/facebook.js",
      "immersion/flickr.js",
      "immersion/youtube.js",
      "immersion/maps.js",
      "immersion/reddit.js",
      "immersion/digg.js",
      "immersion/podcasts.js",
      "immersion/delicious.js",
      "immersion/housingmaps.js",
      "immersion/feedburner.js",
      "immersion/twitter.js",
      "immersion/docs.js",
      "immersion/aws.js",
      "immersion/reader.js",
      "immersion/iphone.js",
      "immersion/netflix.js",
      "immersion/year-2007-extras.js",
      "immersion/one-thing-machines.js"
    ],
    "2008": [

      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/technorati.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/friendster.js",
      "immersion/kazaa.js",
      "immersion/myspace.js",
      "immersion/itunes.js",
      "immersion/wordpress.js",
      "immersion/linkedin.js",
      "immersion/adsense.js",
      "immersion/bloglines.js",
      "immersion/gmail.js",
      "immersion/facebook.js",
      "immersion/flickr.js",
      "immersion/youtube.js",
      "immersion/maps.js",
      "immersion/reddit.js",
      "immersion/digg.js",
      "immersion/podcasts.js",
      "immersion/delicious.js",
      "immersion/housingmaps.js",
      "immersion/feedburner.js",
      "immersion/twitter.js",
      "immersion/docs.js",
      "immersion/aws.js",
      "immersion/reader.js",
      "immersion/iphone.js",
      "immersion/netflix.js",
      "immersion/appstore.js",
      "immersion/chrome-browser.js",
      "immersion/android.js",
      "immersion/hulu.js",
      "immersion/github.js"
    ],
    "2009": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/technorati.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/friendster.js",
      "immersion/kazaa.js",
      "immersion/myspace.js",
      "immersion/itunes.js",
      "immersion/wordpress.js",
      "immersion/linkedin.js",
      "immersion/adsense.js",
      "immersion/bloglines.js",
      "immersion/gmail.js",
      "immersion/facebook.js",
      "immersion/flickr.js",
      "immersion/youtube.js",
      "immersion/maps.js",
      "immersion/reddit.js",
      "immersion/digg.js",
      "immersion/podcasts.js",
      "immersion/delicious.js",
      "immersion/housingmaps.js",
      "immersion/feedburner.js",
      "immersion/twitter.js",
      "immersion/docs.js",
      "immersion/aws.js",
      "immersion/reader.js",
      "immersion/iphone.js",
      "immersion/netflix.js",
      "immersion/appstore.js",
      "immersion/chrome-browser.js",
      "immersion/android.js",
      "immersion/hulu.js",
      "immersion/farmville.js",
      "immersion/bing.js",
      "immersion/foursquare.js",
      "immersion/kickstarter.js",
      "immersion/wave.js",
      "immersion/instagram.js",
      "immersion/pinterest.js",
      "immersion/one-thing-machines.js"
    ],
    "2010": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/technorati.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/friendster.js",
      "immersion/kazaa.js",
      "immersion/myspace.js",
      "immersion/itunes.js",
      "immersion/wordpress.js",
      "immersion/linkedin.js",
      "immersion/adsense.js",
      "immersion/bloglines.js",
      "immersion/gmail.js",
      "immersion/facebook.js",
      "immersion/flickr.js",
      "immersion/youtube.js",
      "immersion/maps.js",
      "immersion/reddit.js",
      "immersion/digg.js",
      "immersion/podcasts.js",
      "immersion/delicious.js",
      "immersion/housingmaps.js",
      "immersion/feedburner.js",
      "immersion/twitter.js",
      "immersion/docs.js",
      "immersion/aws.js",
      "immersion/reader.js",
      "immersion/iphone.js",
      "immersion/netflix.js",
      "immersion/appstore.js",
      "immersion/chrome-browser.js",
      "immersion/android.js",
      "immersion/hulu.js",
      "immersion/farmville.js",
      "immersion/bing.js",
      "immersion/foursquare.js",
      "immersion/kickstarter.js",
      "immersion/wave.js",
      "immersion/instagram.js",
      "immersion/pinterest.js",
      "immersion/imgur.js",
      "immersion/year-2010-extras.js"
    ],
    "2011": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/chrome-browser.js",
      "immersion/siri.js",
      "immersion/spotify.js",
      "immersion/facebook.js",
      "immersion/googleplus.js",
      "immersion/snapchat.js",
      "immersion/youtube.js",
      "immersion/android.js",
      "immersion/one-thing-machines.js",
      "immersion/year-2011-extras.js"
    ],
    "2012": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/chrome-browser.js",
      "immersion/instagram.js",
      "immersion/snapchat.js",
      "immersion/one-thing-machines.js",
      "immersion/year-2012-extras.js"
    ],
    "2013": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/facebook.js",
      "immersion/instagram.js",
      "immersion/snapchat.js",
      "immersion/spotify.js",
      "immersion/iphone.js",
      "immersion/netflix.js",
      "immersion/chrome-browser.js",
      "immersion/year-2013-extras.js",
      "immersion/source-flows.js"
    ],
    /* Lean years 2011–2018: year-true modules only. Do not load the 1995–2010 forest. */
    "2015": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/snapchat.js",
      "immersion/chrome-browser.js",
      "immersion/year-2015-extras.js"
    ],

    "2016": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/year-2016-extras.js"
    ],

    "2017": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/year-2017-extras.js"
    ],

    "2018": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/year-2018-extras.js"
    ],

    "2019": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/year-2019-extras.js"
    ],

    "2020": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/year-2020-extras.js",
      "immersion/source-flows.js"
    ],

    "2021": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/year-2021-extras.js",
      "immersion/source-flows.js"
    ],

    "2014": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/year-2014-extras.js",
      "immersion/youtube.js"
    ],
    "2004": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/friendster.js",
      "immersion/kazaa.js",
      "immersion/myspace.js",
      "immersion/itunes.js",
      "immersion/wordpress.js",
      "immersion/linkedin.js",
      "immersion/adsense.js",
      "immersion/bloglines.js",
      "immersion/gmail.js",
      "immersion/facebook.js",
      "immersion/flickr.js",
      "immersion/digg.js",
      "immersion/technorati.js",
      "immersion/delicious.js",
      "immersion/orkut.js",
      "immersion/livejournal.js",
      "immersion/craigslist.js",
      "immersion/netflix.js",
      "immersion/one-thing-machines.js",
      "immersion/source-flows.js"
    ],
    "2003": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/technorati.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/friendster.js",
      "immersion/kazaa.js",
      "immersion/myspace.js",
      "immersion/itunes.js",
      "immersion/wordpress.js",
      "immersion/linkedin.js",
      "immersion/adsense.js",
      "immersion/bloglines.js",
      "immersion/netflix.js",
      "immersion/photobucket.js",
      "immersion/source-flows.js"
    ],
    "2002": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/technorati.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/friendster.js",
      "immersion/kazaa.js",
      "immersion/netflix.js",
      "immersion/one-thing-machines.js"
    ],
    "2001": [
      "immersion/shared.js",
      "immersion/residual-placard.js",
      "immersion/real-gate.js",
      "immersion/residual-real.js",
      "immersion/real-flow.js",
      "immersion/year-extras-kit.js",
      "immersion/year-5x-pack.js",
      "immersion/year-true-packs.js",
      "immersion/flow-map.js",
      "immersion/year-playable.js",
      "immersion/guestbook-search.js",
      "immersion/amazon.js",
      "immersion/auction.js",
      "immersion/geocities.js",
      "immersion/slashdot.js",
      "immersion/google.js",
      "immersion/excite.js",
      "immersion/yahoo.js",
      "immersion/napster.js",
      "immersion/blogger.js",
      "immersion/plugin.js",
      "immersion/msn.js"
    ]
  };

  /* Ten link-flows: load before flow-map so map pages can list them. */
  (function insertFlowTrails() {
    var map = ITT.IMMERSION_FEATURES_BY_YEAR;
    var y;
    for (y in map) {
      if (!Object.prototype.hasOwnProperty.call(map, y)) continue;
      var list = map[y];
      var i;
      var has = false;
      var before = -1;
      for (i = 0; i < list.length; i++) {
        if (list[i] === "immersion/flow-trails.js") has = true;
        if (list[i] === "immersion/flow-map.js" && before < 0) before = i;
      }
      if (has) continue;
      if (before >= 0) list.splice(before, 0, "immersion/flow-trails.js");
      else list.push("immersion/flow-trails.js");
    }
  })();

  ITT.immersionConfigFile = function (year) {
    return "immersion-" + year + ".js";
  };
})(typeof window !== "undefined" ? window : this);
