export const TRAIL_2018 = [
  { n: 1, name: "GDPR Manage", whenKey: "itt18-gdpr", next: "TikTok For You", year: "2018", leftover: false, fact: "25 May 2018. Manage is the save. Accept All writes nothing. Empty / trap never write.", checks: ["Honesty. Empty never writes.", "This dest is the year star."], trap: "Accept All", verb: "Save preferences", placeholder: "analytics leftover" },
  { n: 2, name: "TikTok For You", whenKey: "itt18-tiktok-fyp", next: "Hearing", year: "2018", leftover: false, fact: "2 Aug 2018 musical.ly merge. For You is the 2018 feed leftover. Not Reels. Not the GDPR star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Accept All (trap)", verb: "For You", placeholder: "For You leftover" },
  { n: 3, name: "Hearing", whenKey: "itt18-hearing", next: "IGTV", year: "2018", leftover: false, fact: "April 2018. Zuckerberg sits. Cambridge Analytica is the weather. Literacy. No partisan dest.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Skip", verb: "I was there", placeholder: "hearing leftover" },
  { n: 4, name: "IGTV", whenKey: "itt18-igtv", next: "Chrome 68", year: "2018", leftover: false, fact: "June 2018. Vertical long video. Not Stories. Not Reels. Not the GDPR star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Stories as gold (trap)", verb: "Upload leftover", placeholder: "episode leftover" },
  { n: 5, name: "Chrome 68", whenKey: "itt18-not-secure", next: "HomePod", year: "2018", leftover: false, fact: "July 2018. HTTP marked Not Secure. The padlock leftover. Not Chromium Edge.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Already HTTPS (trap)", verb: "See Not Secure", placeholder: "not secure leftover" },
  { n: 6, name: "HomePod", whenKey: "itt18-homepod", next: "Spectre", year: "2018", leftover: false, fact: "Feb 2018 shipping. Siri leftover speaker. Not Alexa. Not the GDPR star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Alexa as gold (trap)", verb: "Hey Siri leftover", placeholder: "HomePod leftover" },
  { n: 7, name: "Spectre", whenKey: "itt18-spectre", next: "Fortnite on Switch", year: "2018", leftover: false, fact: "Jan 2018. Speculative leftover. Literacy only. No exploit. No payload.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Run payload (trap)", verb: "Patch leftover", placeholder: "Spectre leftover" },
  { n: 8, name: "Fortnite on Switch", whenKey: "itt18-fn-switch", next: "GitHub $7.5B", year: "2018", leftover: false, fact: "June 2018. Free on Switch. Not the 2017 Battle Royale star. Not GDPR.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "2017 drop as gold (trap)", verb: "Play leftover", placeholder: "Switch leftover" },
  { n: 9, name: "GitHub $7.5B", whenKey: "itt18-github", next: "Consent Dash", year: "2018", leftover: false, fact: "June 2018. Microsoft announces it will buy GitHub for $7.5B. Work graph leftover. Not the GDPR star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Accept All (trap)", verb: "Ack leftover", placeholder: "GitHub leftover" },
  { n: 10, name: "Consent Dash", whenKey: "itt18-game-consentdash", next: "GDPR Manage", year: "2018", leftover: false, fact: "Museum original. Cookie-banner dash. Manage is still the star. Accept All never writes.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Accept All (trap)", verb: "Dash leftover", placeholder: "consent leftover" },
];
export const ALSO_2018 = [
  { n: 11, name: "Sunset leftover", whenKey: "itt18-gplusgone-lx", next: "Gesture leftover", year: "2018", leftover: true, fact: "Google+ consumer shutdown announced 8 Oct 2018, offline 2 Apr 2019. Dual-date leftover. Not the GDPR star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Sunset leftover", placeholder: "sunset leftover" },
  { n: 12, name: "Gesture leftover", whenKey: "itt18-androidpie-lx", next: "Screen Time leftover", year: "2018", leftover: true, fact: "Android 9 Pie 2018. Gesture leftover. Not iOS 12. Not the GDPR star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Gesture leftover", placeholder: "gesture leftover" },
  { n: 13, name: "Screen Time leftover", whenKey: "itt18-ios12-lx", next: "Drop leftover", year: "2018", leftover: true, fact: "iOS 12 Screen Time 17 Sep 2018. Not Face ID (2017). Not the GDPR star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Screen Time leftover", placeholder: "screen time leftover" },
  { n: 14, name: "Drop leftover", whenKey: "itt18-pubg-lx", next: "Ride leftover", year: "2018", leftover: true, fact: "PUBG leftover. Fortnite on Switch is official n=8. Never writes GDPR.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Drop leftover", placeholder: "pubg leftover" },
  { n: 15, name: "Ride leftover", whenKey: "itt18-rdr2-lx", next: "Update leftover", year: "2018", leftover: true, fact: "Red Dead Redemption 2 26 Oct 2018. Ride leftover. Not the GDPR star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Ride leftover", placeholder: "rdr2 leftover" },
  { n: 16, name: "Update leftover", whenKey: "itt18-mojave-lx", next: "Resolve leftover", year: "2018", leftover: true, fact: "macOS Mojave 24 Sep 2018. Update leftover. Not Catalina (2019). Not the GDPR star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Update leftover", placeholder: "mojave leftover" },
  { n: 17, name: "Resolve leftover", whenKey: "itt18-onedot-lx", next: "Install leftover", year: "2018", leftover: true, fact: "1.1.1.1 resolver 1 Apr 2018. Resolve leftover. Not the GDPR star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Resolve leftover", placeholder: "1.1.1.1 leftover" },
  { n: 18, name: "Install leftover", whenKey: "itt18-epicstore-lx", next: "Subscribe leftover", year: "2018", leftover: true, fact: "Epic Games Store 6 Dec 2018. Install leftover. Not Fortnite on Switch. Not the GDPR star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Install leftover", placeholder: "epic leftover" },
  { n: 19, name: "Subscribe leftover", whenKey: "itt18-nso-lx", next: "Stream leftover", year: "2018", leftover: true, fact: "Nintendo Switch Online 18 Sep 2018. Subscribe leftover. Not Fortnite on Switch. Not the GDPR star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Subscribe leftover", placeholder: "nso leftover" },
  { n: 20, name: "Stream leftover", whenKey: "itt18-espnplus-lx", next: "Go live leftover", year: "2018", leftover: true, fact: "ESPN+ 12 Apr 2018. Stream leftover. Not Disney+ (2019). Not the GDPR star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Stream leftover", placeholder: "espn leftover" },
  { n: 21, name: "Go live leftover", whenKey: "itt18-caffeine-lx", next: "GDPR Manage", year: "2018", leftover: true, fact: "Caffeine live leftover 2018. Not Twitch DROP. Not the GDPR star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Accept All (trap)", verb: "Go live leftover", placeholder: "caffeine leftover" },
];
export const ALL_2018 = TRAIL_2018.concat(ALSO_2018);
export const GUIDED_2018 = [
  ["About 2018", "about"],
  ["GDPR Manage", "itt18-gdpr"],
  ["TikTok For You", "itt18-tiktok-fyp"],
  ["Hearing", "itt18-hearing"],
  ["IGTV", "itt18-igtv"],
  ["Year flow map", "map"],
];
export function stopByKey2018(key) {
  return ALL_2018.find((stop) => stop.whenKey === key) || null;
}
