export const TRAIL_2017 = [
  { n: 1, name: "Face ID / iPhone X", whenKey: "itt17-faceid", next: "Fortnite BR", year: "2017", leftover: false, fact: "No Home. Look. Swipe up. Face ID is the 2017 star. Empty / trap never write.", checks: ["I looked."], trap: "Home button (trap)", verb: "Swipe up", placeholder: "Look" },
  { n: 2, name: "Fortnite BR", whenKey: "itt17-fortnite", next: "Twitter 280", year: "2017", leftover: false, fact: "Free storm. 100. Drop from the bus. Not the Face ID star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Face ID as gold (trap)", verb: "Drop from the bus", placeholder: "Fortnite Battle Royale" },
  { n: 3, name: "Twitter 280", whenKey: "itt17-twitter-280", next: "Teams GA", year: "2017", leftover: false, fact: "280 characters. Tweet is the save. Not the Face ID star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Face ID as gold (trap)", verb: "Tweet", placeholder: "What's happening" },
  { n: 4, name: "Teams GA", whenKey: "itt17-teams", next: "Vine gone", year: "2017", leftover: false, fact: "Work chat GA. Create team is the save. Not the Face ID star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Face ID as gold (trap)", verb: "Create team", placeholder: "Team name" },
  { n: 5, name: "Vine gone", whenKey: "itt17-vine-gone", next: "Nintendo Switch", year: "2017", leftover: false, fact: "The loops stay a website. The app is gone. 2016 announced it. Not the Face ID star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Face ID as gold (trap)", verb: "I was there", placeholder: "Vine is gone" },
  { n: 6, name: "Nintendo Switch", whenKey: "itt17-switch", next: "WannaCry", year: "2017", leftover: false, fact: "Mar 2017. Handheld leftover console. Fortnite-on-Switch is 2018. Not the Face ID star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Face ID as gold (trap)", verb: "Reserve", placeholder: "Nintendo Switch" },
  { n: 7, name: "WannaCry", whenKey: "itt17-wannacry", next: "musical.ly", year: "2017", leftover: false, fact: "May 2017. Literacy. Patch is the save. No exploit. No payload.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Run payload (trap)", verb: "Patch", placeholder: "WannaCry" },
  { n: 8, name: "musical.ly", whenKey: "itt17-musically", next: "Equifax freeze", year: "2017", leftover: false, fact: "Lip-sync leftover. Not TikTok US mass (2018). Not the Face ID star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Face ID as gold (trap)", verb: "Post leftover", placeholder: "caption" },
  { n: 9, name: "Equifax freeze", whenKey: "itt17-equifax", next: "Storm Circle", year: "2017", leftover: false, fact: "Place a freeze. Literacy. No SSN. Not the Face ID star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Face ID as gold (trap)", verb: "Place a freeze", placeholder: "Equifax" },
  { n: 10, name: "Storm Circle", whenKey: "itt17-game-stormcircle", next: "Animoji", year: "2017", leftover: false, fact: "Museum original. The storm is the toy. Face ID is still the star.", checks: ["Honesty. Empty never writes.", "This dest, not the year star."], trap: "Face ID as gold (trap)", verb: "Drop leftover", placeholder: "Storm Circle" },
];
export const ALSO_2017 = [
  { n: 11, name: "Animoji", whenKey: "itt17-animoji", next: "iOS 11", year: "2017", leftover: true, fact: "Animoji leftover. Same dest folder as Face ID. Writes itt17-animoji only. Never writes the star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Save", placeholder: "leftover dest" },
  { n: 12, name: "iOS 11", whenKey: "itt17-ios11", next: "PUBG", year: "2017", leftover: true, fact: "iOS 11 leftover. Control Center leftover. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Install iOS 11", placeholder: "iOS 11" },
  { n: 13, name: "PUBG", whenKey: "itt17-pubgnote", next: "Cuphead", year: "2017", leftover: true, fact: "PUBG leftover. Fortnite BR is official n=2. Never writes Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Land leftover", placeholder: "pubg" },
  { n: 14, name: "Cuphead", whenKey: "itt17-cuphead", next: "Twitter Lite", year: "2017", leftover: true, fact: "Cuphead leftover. Not the Face ID star.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Fight leftover", placeholder: "leftover dest" },
  { n: 15, name: "Twitter Lite", whenKey: "itt17-twitterlite", next: "Snap IPO", year: "2017", leftover: true, fact: "Twitter Lite leftover. 280 is official n=3. Never writes Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Open Lite leftover", placeholder: "lite leftover" },
  { n: 16, name: "Snap IPO", whenKey: "itt17-snapipo", next: "Slack", year: "2017", leftover: true, fact: "Mar 2017 Snap IPO leftover. Literacy. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Ack IPO leftover", placeholder: "leftover dest" },
  { n: 17, name: "Slack", whenKey: "itt17-slack17", next: "Hangouts Chat", year: "2017", leftover: true, fact: "Slack leftover. Teams GA is official n=4. Never writes Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Send leftover", placeholder: "#general leftover" },
  { n: 18, name: "Hangouts Chat", whenKey: "itt17-hangoutschat", next: "Snap Map", year: "2017", leftover: true, fact: "Hangouts Chat leftover. Not Teams. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Send leftover", placeholder: "chat leftover" },
  { n: 19, name: "Snap Map", whenKey: "itt17-snapmap", next: "Instagram 2017", year: "2017", leftover: true, fact: "Snap Map leftover. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Open Map leftover", placeholder: "leftover dest" },
  { n: 20, name: "Instagram 2017", whenKey: "itt17-instagram17", next: "Breath of the Wild", year: "2017", leftover: true, fact: "2017 Instagram leftover. Stories was 2016. Never writes Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Open leftover", placeholder: "leftover dest" },
  { n: 21, name: "Breath of the Wild", whenKey: "itt17-botw", next: "Splatoon 2", year: "2017", leftover: true, fact: "Breath of the Wild leftover. Switch is official n=6. Never writes Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Climb leftover", placeholder: "leftover dest" },
  { n: 22, name: "Splatoon 2", whenKey: "itt17-splatoon2", next: "NotPetya", year: "2017", leftover: true, fact: "Splatoon 2 leftover. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Ink leftover", placeholder: "leftover dest" },
  { n: 23, name: "NotPetya", whenKey: "itt17-notpetya", next: "KRACK", year: "2017", leftover: true, fact: "NotPetya leftover. Literacy. No exploit. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Ack leftover", placeholder: "notpetya" },
  { n: 24, name: "KRACK", whenKey: "itt17-krack", next: "tbh", year: "2017", leftover: true, fact: "KRACK leftover. Literacy. No exploit. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Ack leftover", placeholder: "leftover dest" },
  { n: 25, name: "tbh", whenKey: "itt17-tbh", next: "Messenger Day", year: "2017", leftover: true, fact: "tbh leftover. Poll leftover. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Vote leftover", placeholder: "leftover dest" },
  { n: 26, name: "Messenger Day", whenKey: "itt17-messengerday", next: "Credit freeze", year: "2017", leftover: true, fact: "Messenger Day leftover. Not Stories. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Post leftover", placeholder: "leftover dest" },
  { n: 27, name: "Credit freeze", whenKey: "itt17-creditfrz", next: "Cloudbleed", year: "2017", leftover: true, fact: "Credit freeze leftover. Equifax freeze is official n=9. Never writes Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Note freeze leftover", placeholder: "leftover dest" },
  { n: 28, name: "Cloudbleed", whenKey: "itt17-cloudbleed", next: "Getting Over It", year: "2017", leftover: true, fact: "Cloudbleed leftover. Rotate leftover. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Rotate leftover", placeholder: "leftover dest" },
  { n: 29, name: "Getting Over It", whenKey: "itt17-gettingoverit", next: "Hollow Knight", year: "2017", leftover: true, fact: "Getting Over It leftover. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Climb leftover", placeholder: "leftover dest" },
  { n: 30, name: "Hollow Knight", whenKey: "itt17-hollowknight", next: "Face ID / iPhone X", year: "2017", leftover: true, fact: "Hollow Knight leftover. Not Face ID.", checks: ["The chip is not this dest.", "Empty / trap never write."], trap: "Face ID as gold (trap)", verb: "Rest leftover", placeholder: "leftover dest" },
];
export const ALL_2017 = TRAIL_2017.concat(ALSO_2017);
export const GUIDED_2017 = [
  ["About 2017", "about"],
  ["Face ID / iPhone X", "itt17-faceid"],
  ["Fortnite BR", "itt17-fortnite"],
  ["Twitter 280", "itt17-twitter-280"],
  ["Teams GA", "itt17-teams"],
  ["Year flow map", "map"],
];
export function stopByKey2017(key) {
  return ALL_2017.find((stop) => stop.whenKey === key) || null;
}
