/** Official 2014 trail. Same order and keys as js/config/flow-trails.js. */
export const TRAIL_2014 = [
  {
    n: 1,
    name: "WhatsApp",
    href: "/years/2014/sites/whatsapp/index.html",
    whenKey: "itt14-wa-install",
    next: "Heartbleed",
    field: false,
    fact: "19 Feb 2014. $19 billion. Messenger stays a separate app. WhatsApp Web is 2015.",
    checks: [
      "Honesty. Empty / trap never writes.",
      "This dest, not neighbor-year gold.",
    ],
    trap: "Open Messenger instead",
    verb: "Install",
  },
  {
    n: 2,
    name: "Heartbleed",
    href: "/years/2014/sites/heartbleed/index.html",
    whenKey: "itt14-heartbleed",
    next: "Ice Bucket",
    fact: "CVE-2014-0160. Public 7 Apr 2014. Literacy and rotate. No exploit.",
    checks: ["Honesty. Empty never writes.", "This dest, not the year star."],
    trap: "Star as gold (trap)",
    verb: "Heartbleed",
    placeholder: "Heartbleed",
  },
  {
    n: 3,
    name: "Ice Bucket",
    href: "/years/2014/sites/icebucket/index.html",
    whenKey: "itt14-icebucket",
    next: "iPhone 6",
    fact: "ALS, July–August 2014. Nominate and a summer note. No dump.",
    checks: ["Honesty. Empty never writes.", "This dest, not the year star."],
    trap: "Star as gold (trap)",
    verb: "Ice Bucket",
    placeholder: "Ice Bucket",
  },
  {
    n: 4,
    name: "iPhone 6",
    href: "/years/2014/sites/iphone/index.html",
    whenKey: "itt14-iphone6",
    next: "Apple Pay",
    fact: "Announced 9 Sep 2014. Ships 19 Sep. Watch is announced here and ships in 2015.",
    checks: ["Honesty. Empty never writes.", "This dest, not the year star."],
    trap: "Star as gold (trap)",
    verb: "iPhone 6",
    placeholder: "iPhone 6",
  },
  {
    n: 5,
    name: "Apple Pay",
    href: "/years/2014/sites/applepay/index.html",
    whenKey: "itt14-applepay",
    next: "Material",
    fact: "NFC and Touch ID. Not a card form. Watch ships in 2015.",
    checks: [
      "NFC + Touch ID. Not a card form.",
      "Watch ships 2015. This dest is not WhatsApp gold.",
    ],
    trap: "Open checkout (trap)",
    verb: "Save Pay literacy",
    placeholder: "NFC + Touch ID note",
  },
  {
    n: 6,
    name: "Material",
    href: "/years/2014/sites/material/index.html",
    whenKey: "itt14-material",
    next: "Slack",
    fact: "Google I/O 25 Jun 2014. Lollipop 12 Nov. Paper and ink.",
    checks: ["Honesty. Empty never writes.", "This dest, not the year star."],
    trap: "Star as gold (trap)",
    verb: "Material",
    placeholder: "Material",
  },
  {
    n: 7,
    name: "Slack",
    href: "/years/2014/sites/slack/index.html",
    whenKey: "itt14-slack",
    next: "Twitch",
    fact: "Public 12 Feb 2014. Email bankruptcy. Pick a channel, then join.",
    checks: ["Honesty. Empty never writes.", "This dest, not the year star."],
    trap: "Star as gold (trap)",
    verb: "Slack",
    placeholder: "Slack",
  },
  {
    n: 8,
    name: "Twitch",
    href: "/years/2014/sites/twitch/index.html",
    whenKey: "itt14-twitch",
    next: "Tile Fold",
    fact: "Amazon bought Twitch for $970 million on 25 Aug 2014. Google-bought is the trap.",
    checks: ["Honesty. Empty never writes.", "This dest, not the year star."],
    trap: "Star as gold (trap)",
    verb: "Twitch",
    placeholder: "Twitch",
  },
  {
    n: 9,
    name: "Tile Fold",
    href: "/years/2014/sites/playable/game.html",
    whenKey: "itt14-game-tilefold",
    next: "WhatsApp",
    fact: "Fold two tiles. Flappy is not the gold. Load never writes.",
    checks: ["Honesty. Empty never writes.", "This dest, not the year star."],
    trap: "Star as gold (trap)",
    verb: "Tile Fold",
    placeholder: "Tile Fold",
  },
];

export const START_2014 = "/years/2014/pages/home.html";

export const GUIDED_2014 = [
  ["About 2014", "/years/2014/pages/about.html", null],
  ["WhatsApp", "/years/2014/sites/whatsapp/index.html", "itt14-wa-install"],
  ["Heartbleed", "/years/2014/sites/heartbleed/index.html", "itt14-heartbleed"],
  ["Ice Bucket", "/years/2014/sites/icebucket/index.html", "itt14-icebucket"],
  ["iPhone 6", "/years/2014/sites/iphone/index.html", "itt14-iphone6"],
  ["Year flow map", "/years/2014/pages/map.html", null],
];

export function stopByKey(key) {
  return TRAIL_2014.find((stop) => stop.whenKey === key) || null;
}
