#!/usr/bin/env python3
"""Generate js/browser-YYYY.js and js/immersion-YYYY.js for HTML ship years. Do not hand-fork.

Years come from js/year-card.json via HTML_SHIP_YEARS in scripts/itt_gate.py.
React 2015 and absent years (2017–2019, 2023–2025) are not written.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from itt_gate import HTML_SHIP_YEARS  # noqa: E402

YEARS = list(HTML_SHIP_YEARS)

BROWSER = """/**
 * Browser year stub — {year}
 * GENERATED by scripts/gen_year_shims.py — do not hand-fork.
 */
(function () {{
  "use strict";
  if (window.ITT && ITT.bootBrowserYear) {{
    ITT.bootBrowserYear("{year}");
    return;
  }}
  if (!window.ITT || !ITT.Browser || !ITT.configs || !ITT.configs["{year}"]) {{
    console.error("ITT {year} bootstrap: missing util/core/config scripts");
    return;
  }}
  ITT.Browser.create(ITT.configs["{year}"]);
}})();
"""

IMMERSION = """/**
 * Immersion year stub — {year}
 * GENERATED by scripts/gen_year_shims.py — do not hand-fork.
 */
(function () {{
  "use strict";
  var ITT = window.ITT || (window.ITT = {{}});
  ITT._immersionYear = "{year}";
  var scripts = document.getElementsByTagName("script");
  var me = document.currentScript || scripts[scripts.length - 1];
  var base = (me && me.src) ? me.src.replace(/\\/[^/]*$/, "/") : "/js/";
  var el = document.createElement("script");
  el.src = base + "immersion/boot.js?v=20261004glass";
  el.async = true;
  (document.head || document.documentElement).appendChild(el);
}})();
"""


def main() -> None:
    js = ROOT / "js"
    for year in YEARS:
        (js / f"browser-{year}.js").write_text(BROWSER.format(year=year))
        (js / f"immersion-{year}.js").write_text(IMMERSION.format(year=year))
        print("wrote", year)


if __name__ == "__main__":
    main()
