#!/usr/bin/env python3
"""Write js/year-card.js from js/year-card.json.

The JSON file is the door list. Do not hand-edit the browser copy.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CARD = ROOT / "js" / "year-card.json"
OUT = ROOT / "js" / "year-card.js"


def main() -> None:
    card = json.loads(CARD.read_text(encoding="utf-8"))
    body = json.dumps(card, indent=2, ensure_ascii=False)
    text = (
        "/** One year card. Canonical data is js/year-card.json. Generated by scripts/gen_year_card.py. */\n"
        "(function (global) {\n"
        '  "use strict";\n'
        "  var ITT = global.ITT || (global.ITT = {});\n"
        "  ITT.YEAR_CARD = "
        + body
        + ";\n"
        '})(typeof window !== "undefined" ? window : this);\n'
    )
    OUT.write_text(text, encoding="utf-8")
    print("wrote", OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
