#!/usr/bin/env python3
"""Generate js/browser-YYYY.js and js/immersion-YYYY.js. Do not hand-fork."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
YEARS = [str(y) for y in range(1994, 2023)]

BROWSER = """/**
 * Browser year stub — {year}
 * GENERATED by scripts/gen_year_shims.py — do not hand-fork.
 */
(function () {{
  "use strict";
  if (window.ITT && ITT.bootBrowserYear) {{
    ITT.bootBrowserYear("{year}");
    return;
  }}
  if (!window.ITT || !ITT.Browser || !ITT.configs || !ITT.configs["{year}"]) {{
    console.error("ITT {year} bootstrap: missing util/core/config scripts");
    return;
  }}
  ITT.Browser.create(ITT.configs["{year}"]);
}})();
"""

IMMERSION = """/**
 * Immersion year stub — {year}
 * GENERATED by scripts/gen_year_shims.py — do not hand-fork.
 */
(function () {{
  "use strict";
  var ITT = window.ITT || (window.ITT = {{}});
  ITT._immersionYear = "{year}";
  var scripts = document.getElementsByTagName("script");
  var me = document.currentScript || scripts[scripts.length - 1];
  var base = (me && me.src) ? me.src.replace(/\\/[^/]*$/, "/") : "/js/";
  var el = document.createElement("script");
  el.src = base + "immersion/boot.js?v=20260921boot2";
  el.async = true;
  (document.head || document.documentElement).appendChild(el);
}})();
"""


def main() -> None:
    js = ROOT / "js"
    for year in YEARS:
        (js / f"browser-{year}.js").write_text(BROWSER.format(year=year))
        (js / f"immersion-{year}.js").write_text(IMMERSION.format(year=year))
        print("wrote", year)


if __name__ == "__main__":
    main()
